🔄 Sync: Changes from tree-sitter repo
legesher/tree-sitter-legesher-python pull request #76
Opened 2020-10-03 22:44 UTC by alxnull

## 🔄 Sync: Changes from tree-sitter repo

This pull request (PR) is made in reference to: #70

## Description

Sync changes from tree-sitter repo, as mentioned in #70 (closes #70).

- closes #66
- closes #68 
- closes #69 (seems to be empty?)
- closes #73

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

## Testing

* [x] My submission passes the tests?

2020-10-10 17:03 UTC, madiedgar commented
@alxnull thank you so much for this!! I'll look into this today 👍

2020-10-14 20:28 UTC, madiedgar requested changes
Thank you @alxnull for this thorough contribution! Its extremely helpful. 👍  Made a couple of change requests, but other than that this looks great!!

2020-10-14 20:28 UTC, madiedgar commented on package.json
> +    "tree-sitter-cli": "^0.16.9",
**Line 4-6: the `details` object**

Can you update both attributes within this object to reflect the current synced version of `tree-sitter/tree-sitter-python`? This helps us stay up to date with new commits to their repository. 👍  So for instance, `"latest-commit": "58f57240834d6b88624e32ad0ab9531d55fb7a5d"`. 

(This isn't for line 33, but I can't review the line that needs updating.)

2020-10-14 20:28 UTC, madiedgar commented on queries/highlights.scm
**Lines 9-24: `Function Calls` and `Builtin Functions`**

Not sure why they went for such a change, but these two sections were reordered to have `Builtin functions` to be before `Function calls`. For consistency sake, can we do the same? 

(again, sorry for the misplaced comment)

2020-10-16 18:15 UTC, alxnull commented
@madiedgar thanks for the feedback! I implemented the changes you suggested.

2020-10-17 05:40 UTC, madiedgar approved these changes

2020-10-29 07:51 UTC, merged